#!/bin/bash
#<<COMMENT1
#COMMENT1
for i in \
    isobands-simple \
    isobands-breaks\
    geotiff-isobands; do
   test/render-isobands.js $i \
      && [ "$(compare -metric rmse test/samples/$i.png test/output/$i.png null: 2>&1)" = "0 (0)" ] \
      || echo "✗ test/output/$i.png and test/samples/$i.png differ"
done


for i in \
    isolines-simple \
    isolines-breaks\
    geotiff-isolines; do
   test/render-isolines.js $i \
      && [ "$(compare -metric rmse test/samples/$i.png test/output/$i.png null: 2>&1)" = "0 (0)" ] \
      || echo "✗ test/output/$i.png and test/samples/$i.png differ"
done
